CREATE TABLE Automovel (
    PLACA VARCHAR(10) PRIMARY KEY,
    cor VARCHAR(50) NOT NULL,
    Chassis VARCHAR(50) NOT NULL,
    Modelo VARCHAR(50) NOT NULL,
    Direção_Assistida BOOLEAN NOT NULL,
    Ar_condicionado BOOLEAN NOT NULL,
    Manutenção BOOLEAN NOT NULL,
    Nro_de_Porta INTEGER NOT NULL,
    Quilometragem INTEGER NOT NULL,
    Transmissão VARCHAR(20) NOT NULL,
    Marca VARCHAR(50) NOT NULL,
    Tipo_de_combustivel VARCHAR(20) NOT NULL,
    Renavam VARCHAR(20) NOT NULL,
    Tipo VARCHAR(20) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    Valor DECIMAL(10, 2) NOT NULL
);

CREATE TABLE Locacao (
    COD_LOCACAO SERIAL PRIMARY KEY,
    cod_automovel VARCHAR(10) NOT NULL,
    Valor_total DECIMAL(10, 2) NOT NULL,
    Data_devolução DATE NOT NULL,
    Data_alocação DATE NOT NULL,
    FOREIGN KEY (cod_automovel) REFERENCES Automovel (PLACA)
);

CREATE TABLE Usuario (
    COD_USUARIO SERIAL PRIMARY KEY,
    Data_nascimento DATE NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    Rua VARCHAR(100) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Bairro VARCHAR(50) NOT NULL
);

CREATE TABLE Funcionario (
    COD_FUNCIONARIO INTEGER PRIMARY KEY,
    Função VARCHAR(50) NOT NULL,
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES Usuario (COD_USUARIO)
);

CREATE TABLE Cliente (
    COD_CLIENTE INTEGER PRIMARY KEY,
    Carteira_de_motorista VARCHAR(20) NOT NULL,
    FOREIGN KEY (COD_CLIENTE) REFERENCES Usuario (COD_USUARIO)
);

CREATE TABLE Reserva (
    COD_RESERVA SERIAL PRIMARY KEY,
    COD_LOCACAO INTEGER NOT NULL,
    COD_CLIENTE INTEGER NOT NULL,
    COD_AUTOMOVEL VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    FOREIGN KEY (COD_LOCACAO) REFERENCES Locacao (COD_LOCACAO),
    FOREIGN KEY (COD_CLIENTE) REFERENCES Cliente (COD_CLIENTE),
    FOREIGN KEY (COD_AUTOMOVEL) REFERENCES Automovel (PLACA)
);
